name: algorithm_dart
description: 使用 dart 实现常见的算法
# version: 1.0.0
# homepage: https://github.com/yy1300326388/algorithm_dart
# author: Zero <zhengsonglan001@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
